### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by zhengshifa** [reworkd/AgentGPT#123] opened 2023-04-14 13:34 UTC
After clicking deploy, there is an exception

**Comment by yourepicservices** [comment] 2023-04-15 18:06
@zhengshifa, could you please provide the console log when encountering this error along with the browser you're using?

**Comment by JNaeemGitonga** [comment] 2023-04-16 19:46
I've seen the following:
```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```
But I wasn't able to consistently reproduce it. In fact, I only saw it once...

**Comment by yourepicservices** [comment] 2023-04-17 02:28
Were you accessing the app from the same machine that it was running on? The only thing that comes to mind right away is lag or something.

**Comment by Deadzone2023** [comment] 2023-04-18 13:32
Application error: a client-side exception has occurred (see the browser console for more information). Here's what appears when I activate the agent

**Comment by yourepicservices** [comment] 2023-04-19 00:54
@Deadzone2023 what error shows up in the browser console?

**Comment by asim-shrestha** [comment] 2023-04-23 23:19
Hey folks, can you provide any more context here? Are you still facing this issue? @Deadzone2023 @JNaeemGitonga

**Comment by JNaeemGitonga** [comment] 2023-04-23 23:25
> Hey folks, can you provide any more context here? Are you still facing this issue? @Deadzone2023 @JNaeemGitonga

As I said, I wasn't able to consistently reproduce it.

**Comment by asim-shrestha** [comment] 2023-05-10 23:22
Gotcha,

The original issue here may be related to this ticket which contains a reproducible link: https://github.com/reworkd/AgentGPT/issues/448

**Comment by DabCSon** [comment] 2023-06-17 07:13
Hi, I also have this problem. It says
"Application error: a client-side exception has occurred (see the browser console for more information)."

I'm not sure how to properly show the error. I've linked a picture of it

![D2error](https://github.com/reworkd/AgentGPT/assets/136883666/64247892-0fe3-4f53-b097-86496ac0d5fc)

**Comment by asim-shrestha** [comment] 2023-06-27 20:46
Closing this, the above ticket is now functional. It was an issue with how we were handling translations

**Closed** 2023-07-08 18:54 UTC
Labels: bug

**Comment by tobi9000** [comment] 2023-07-13 07:39
I have the same error with all browsers and platforms. The link above doesn't provide a solution!

I can login but if I click on the tab "Stream Keys" in Configurations, I'm getting: "Application error: a client-side exception has occurred".

I guess that's because no stream key is set. Can anyone give me the line how to set a stream key from CLI? The API documentation doesn't help, could anyone give me the direct command for CLI?

**Comment by asim-shrestha** [comment] 2023-07-15 02:49
Hey @tobi9000 I don't think we have `Stream Keys` setting. Are you talking about https://agentgpt.reworkd.ai/settings or a different app?
