### ISSUE TITLE
🐛 Unhandled Runtime Error

### ISSUE THREAD

**Issue by qq-740943515** [reworkd/AgentGPT#256] opened 2023-04-19 14:51 UTC
![image](https://user-images.githubusercontent.com/60562973/233113984-433b2c2f-f4e0-4ebc-85c1-e5a1df666b75.png)
I don't know why

**Comment by asim-shrestha** [comment] 2023-04-19 16:55
Also, potential duplicate of #212

**Comment by qq-740943515** [comment] 2023-04-21 14:25
agent deployment；yes；the latest version；windows 10

**Comment by asim-shrestha** [comment] 2023-04-23 08:10
Are you still receiving this issue?

**Comment by l2hyunwoo** [comment] 2023-04-24 13:44
@asim-shrestha I am looking forward to solving it with this [PR](https://github.com/reworkd/AgentGPT/pull/309).

**Comment by asim-shrestha** [comment] 2023-05-10 23:37
Appreciate it @l2hyunwoo! Closing

**Closed by asim-shrestha** 2023-05-10 23:37 UTC
