### ISSUE TITLE
点击部署之后就一直是这个问题，显示一个未处理的运行时错误

### ISSUE THREAD

**Issue by sxs123-m** [reworkd/AgentGPT#170] opened 2023-04-16 03:48 UTC
一直是这个错误

 1个未处理错误中的1 个

未处理的运行时错误
NotFoundError ： 无法在“节点”上执行“removeChild”：要删除的节点不是该节点的子节点。

调用堆栈
删除孩子
node_modules\react-dom\cjs\react-dom.development.js (11099:0)
commitDeletionEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24028:0)
提交删除效果
node_modules\react-dom\cjs\react-dom.development.js (23976:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24259:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24576:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24576:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24346:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24576:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24576:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24576:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)
commitMutationEffectsOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24293:0)
递归遍历 MutationEffects
node_modules\react-dom\cjs\react-dom.development.js (24273:0)

**Comment by mosezh** [comment] 2023-04-16 07:23
不要用中文部署

**Comment by hemangjoshi37a** [comment] 2023-04-16 12:01
Hi @sxs123-m, 

Based on the error message you provided, it seems like there is an issue with removing a child node that is not a child of the current node. This can happen if there is a mismatch between the virtual DOM and the actual DOM.

One possible solution is to try clearing the cache or cookies of your browser and trying again. Another solution is to try deploying again after some time, as this could be a temporary issue.

If the issue persists, please provide more information such as the steps to reproduce the error and any relevant code or screenshots. 

Hope this helps!

**Comment by asim-shrestha** [comment] 2023-05-10 23:38
Hey are you still experiencing this? This appears to have been fixed in #256

**Comment by jasangill1** [comment] 2023-07-08 17:52
Hello @sxs123-m were you able to try out the solutions?? I will be closing this due to inactivity. PLease feel free to reopen this if still experiencing these issues!! 😄

**Closed by jasangill1** 2023-07-08 17:52 UTC
