### ISSUE TITLE
Stops at the 3rd thinking step

### ISSUE THREAD

**Issue by aminblm** [reworkd/AgentGPT#2] opened 2023-04-09 07:28 UTC
- Stops at the 3rd thinking step

![image](https://user-images.githubusercontent.com/25132838/230760096-2d03c144-5ef7-4955-b65b-292731bb69e7.png)

**Comment by Srijan-Subedi** [comment] 2023-04-09 18:16
Thanks for letting us know about this! We are currently looking into this

**Comment by hafidzwibowo** [comment] 2023-04-10 12:34
i think maybe its because of the start prompt ""You are an autonomous task creation AI called AgentGPT. You have the following objective `{goal}`. Create a list of zero to three tasks to be completed by your AI system such that your goal is more closely reached or completely reached. Return the response as an array of strings that can be used in JSON.parse()".  then the loop just running on three times. CMIIW just imaging

**Comment by mrayonnaise** [comment] 2023-04-11 21:25
With the latest from the `main` branch I am no longer able to reproduce this. Anyone else?

**Comment by yourepicservices** [comment] 2023-04-15 18:41
@aminblm are you able to reproduce this issue with the latest release?

**Comment by asim-shrestha** [comment] 2023-04-23 23:11
Hey folks, seems like this issue has been fixed now - Closing

**Closed by asim-shrestha** 2023-04-23 23:11 UTC
Labels: bug
